import type { PersistedCommunityRecord } from "./communityChat.types";
import LNTLogo from "@/assets/LNT.webp";
import SYTLogo from "@/assets/logospeak.webp";

// Fallback community shells used while the real chat API is loading or unavailable.
// Members and messages are intentionally empty so the UI never flashes hardcoded
// mock chat content before the API renders the actual data.
//
// Only Late Night Talk, Speak Your Truth, and Is It Just Me? are open. Every other
// community is locked and surfaces "Join Waitlist" until it is released.
export function buildDefaultCommunities(): PersistedCommunityRecord[] {
  return [
    {
      id: "lnt",
      abbr: "LNT",
      logoUrl: LNTLogo,
      title: "Late Night Talk",
      description: "Real talk after midnight.",
      topic: "What thought has been following you all week?",
      status: "Active",
      createdAt: "2026-04-01T00:00:00.000Z",
      members: [],
      messages: [],
    },
    {
      id: "syt",
      abbr: "SYT",
      logoUrl: SYTLogo,
      title: "Speak Your Truth",
      description: "Say what you've been holding back.",
      topic: "What's something you've been afraid to say out loud?",
      status: "Active",
      createdAt: "2026-04-01T00:00:00.000Z",
      members: [],
      messages: [],
    },
    {
      id: "iijm",
      abbr: "IIM",
      title: "Is It Just Me?",
      description: "It's never just you.",
      topic: "What's something you do or feel that you thought was only you?",
      status: "Active",
      createdAt: "2026-04-01T00:00:00.000Z",
      members: [],
      messages: [],
    },
    {
      id: "li",
      abbr: "LI",
      title: "Lebanon Initiatives",
      description: "Lebanese builders making real moves.",
      topic: "What initiative or project are you working on right now?",
      status: "Early Access",
      locked: true,
      createdAt: "2026-04-01T00:00:00.000Z",
      members: [],
      messages: [],
    },

    {
      id: "the-ick",
      abbr: "ICK",
      logoUrl: "/assets/community-covers/the-ick.svg",
      title: "The Ick",
      description: "Tiny turnoffs, instant ick.",
      topic: "What gave you the ick faster than you expected?",
      status: "Active",
      locked: true,
      createdAt: "2026-06-12T00:00:00.000Z",
      members: [],
      messages: [],
    },
    {
      id: "am-i-evil",
      abbr: "AIE",
      logoUrl: "/assets/community-covers/am-i-evil.svg",
      title: "Am I Evil?",
      description: "Confess. The jury decides.",
      topic: "What choice made you wonder if you were the villain?",
      status: "Active",
      locked: true,
      createdAt: "2026-06-12T00:00:00.000Z",
      members: [],
      messages: [],
    },
    {
      id: "weirdest-thoughts",
      abbr: "MWT",
      logoUrl: "/assets/community-covers/weirdest-thoughts.svg",
      title: "My Weirdest Thoughts",
      description: "Shower thoughts, said anonymously.",
      topic: "What weird thought keeps popping into your head?",
      status: "Active",
      locked: true,
      createdAt: "2026-06-12T00:00:00.000Z",
      members: [],
      messages: [],
    },
    {
      id: "is-this-normal",
      abbr: "ITN",
      logoUrl: "/assets/community-covers/is-this-normal.svg",
      title: "Is This Normal?",
      description: "A quick gut-check from strangers.",
      topic: "What are you wondering is normal right now?",
      status: "Active",
      locked: true,
      createdAt: "2026-06-12T00:00:00.000Z",
      members: [],
      messages: [],
    },
    {
      id: "mancave",
      abbr: "MAN",
      logoUrl: "/assets/community-covers/mancave.svg",
      title: "The Mancave",
      description: "Guy stuff, said straight.",
      topic: "What do men need to talk about more honestly?",
      status: "Active",
      locked: true,
      createdAt: "2026-06-12T00:00:00.000Z",
      members: [],
      messages: [],
    },
    {
      id: "gamer-gang",
      abbr: "GG",
      logoUrl: "/assets/community-covers/gamer-gang.svg",
      title: "Gamer Gang",
      description: "Squads, clutch wins, salty losses.",
      topic: "What game has your attention right now?",
      status: "Active",
      locked: true,
      createdAt: "2026-06-12T00:00:00.000Z",
      members: [],
      messages: [],
    },
    {
      id: "bizniz-minded",
      abbr: "BIZ",
      logoUrl: "/assets/community-covers/bizniz-minded.svg",
      title: "Bizniz Minded",
      description: "Money moves, no guru energy.",
      topic: "What business idea or money lesson are you thinking about?",
      status: "Active",
      locked: true,
      createdAt: "2026-06-12T00:00:00.000Z",
      members: [],
      messages: [],
    },
    {
      id: "match-maker",
      abbr: "MM",
      logoUrl: "/assets/community-covers/match-maker.svg",
      title: "Match Maker",
      description: "Green flags, red flags, honest reads.",
      topic: "What match or dating situation needs a second opinion?",
      status: "Active",
      locked: true,
      createdAt: "2026-06-12T00:00:00.000Z",
      members: [],
      messages: [],
    },
    {
      id: "fucking-bored",
      abbr: "FB",
      logoUrl: "/assets/community-covers/fucking-bored.svg",
      title: "Fucking Bored",
      description: "Chaos for a bored brain.",
      topic: "What should bored people argue about for five minutes?",
      status: "Active",
      locked: true,
      createdAt: "2026-06-12T00:00:00.000Z",
      members: [],
      messages: [],
    },
    {
      id: "advice-now",
      abbr: "ADV",
      logoUrl: "/assets/community-covers/advice-now.svg",
      title: "Advice Now!",
      description: "Fast advice before you overthink.",
      topic: "What do you need advice on right now?",
      status: "Active",
      locked: true,
      createdAt: "2026-06-12T00:00:00.000Z",
      members: [],
      messages: [],
    },
    {
      id: "feeling-like-shit",
      abbr: "FLS",
      logoUrl: "/assets/community-covers/feeling-like-shit.svg",
      title: "I'm feeling like shit honestly...",
      description: "A soft place for heavy days.",
      topic: "What is weighing on you today?",
      status: "Active",
      locked: true,
      createdAt: "2026-06-12T00:00:00.000Z",
      members: [],
      messages: [],
    },
    {
      id: "best-story",
      abbr: "BST",
      logoUrl: "/assets/community-covers/best-story.svg",
      title: "Best story I’ve been told",
      description: "Wild stories worth retelling.",
      topic: "What is the best story someone ever told you?",
      status: "Active",
      locked: true,
      createdAt: "2026-06-12T00:00:00.000Z",
      members: [],
      messages: [],
    },
  ];
}
