// Generated by scripts/process-new-avatars.mjs — do not edit by hand.
// Drop new images in public/avatars/ and run the script (or commit, the
// pre-commit hook runs it for you).
import type { AvatarCatalogItem } from "@/lib/avatarCatalog";

export const GENERATED_AVATAR_ENTRIES: readonly AvatarCatalogItem[] = [
  { id: "avatar-36", level: 36, name: "Avatar 36", price: "50", imageSrc: "/avatars/36.png", bg: "#010501", figure: "#082808", ring: "#082808", glow: "#08280880", isActive: true, showIn: "both", rarity: "common" },
  { id: "avatar-37", level: 37, name: "Avatar 37", price: "50", imageSrc: "/avatars/37.png", bg: "#070509", figure: "#382848", ring: "#382848", glow: "#38284880", isActive: true, showIn: "both", rarity: "common" },
  { id: "avatar-38", level: 38, name: "Avatar 38", price: "50", imageSrc: "/avatars/38.png", bg: "#090501", figure: "#482808", ring: "#482808", glow: "#48280880", isActive: true, showIn: "both", rarity: "common" },
  { id: "avatar-39", level: 39, name: "Avatar 39", price: "50", imageSrc: "/avatars/39.png", bg: "#1e0e0e", figure: "#f87878", ring: "#f87878", glow: "#f8787880", isActive: true, showIn: "both", rarity: "common" },
  { id: "avatar-40", level: 40, name: "Avatar 40", price: "50", imageSrc: "/avatars/40.webp", bg: "#1e1614", figure: "#f8b8a8", ring: "#f8b8a8", glow: "#f8b8a880", isActive: true, showIn: "both", rarity: "common" },
  { id: "avatar-41", level: 41, name: "Avatar 41", price: "50", imageSrc: "/avatars/41.webp", bg: "#160e1e", figure: "#b878f8", ring: "#b878f8", glow: "#b878f880", isActive: true, showIn: "both", rarity: "common" },
  { id: "avatar-42", level: 42, name: "Avatar 42", price: "50", imageSrc: "/avatars/42.webp", bg: "#0b0301", figure: "#581808", ring: "#581808", glow: "#58180880", isActive: true, showIn: "both", rarity: "common" },
  { id: "avatar-43", level: 43, name: "Avatar 43", price: "50", imageSrc: "/avatars/43.webp", bg: "#030509", figure: "#182848", ring: "#182848", glow: "#18284880", isActive: true, showIn: "both", rarity: "common" },
  { id: "avatar-44", level: 44, name: "Avatar 44", price: "50", imageSrc: "/avatars/44.png", bg: "#010b10", figure: "#085888", ring: "#085888", glow: "#08588880", isActive: true, showIn: "both", rarity: "common" },
  { id: "avatar-46", level: 46, name: "Avatar 46", price: "50", imageSrc: "/avatars/46.png", bg: "#18121c", figure: "#c898e8", ring: "#c898e8", glow: "#c898e880", isActive: true, showIn: "both", rarity: "common" },
  { id: "avatar-47", level: 47, name: "Avatar 47", price: "50", imageSrc: "/avatars/47.webp", bg: "#0e0109", figure: "#780848", ring: "#780848", glow: "#78084880", isActive: true, showIn: "both", rarity: "common" },
  { id: "avatar-48", level: 48, name: "Avatar 48", price: "50", imageSrc: "/avatars/48.png", bg: "#010505", figure: "#082828", ring: "#082828", glow: "#08282880", isActive: true, showIn: "admin", rarity: "common" },
  { id: "avatar-49", level: 49, name: "Avatar 49", price: "50", imageSrc: "/avatars/49.png", bg: "#07030b", figure: "#381858", ring: "#381858", glow: "#38185880", isActive: true, showIn: "both", rarity: "common" },
  { id: "avatar-51", level: 51, name: "Avatar 51", price: "50", imageSrc: "/avatars/51.png", bg: "#1a050b", figure: "#d82858", ring: "#d82858", glow: "#d8285880", isActive: true, showIn: "both", rarity: "common" },
  { id: "avatar-52", level: 52, name: "Avatar 52", price: "50", imageSrc: "/avatars/52.webp", bg: "#010505", figure: "#082828", ring: "#082828", glow: "#08282880", isActive: true, showIn: "both", rarity: "common" },
  { id: "avatar-53", level: 53, name: "Avatar 53", price: "50", imageSrc: "/avatars/53.png", bg: "#0b0c01", figure: "#586808", ring: "#586808", glow: "#58680880", isActive: true, showIn: "both", rarity: "common" },
  { id: "avatar-54", level: 54, name: "Avatar 54", price: "50", imageSrc: "/avatars/54.png", bg: "#1a1414", figure: "#d8a8a8", ring: "#d8a8a8", glow: "#d8a8a880", isActive: true, showIn: "both", rarity: "common" },
  { id: "avatar-55", level: 55, name: "Avatar 55", price: "50", imageSrc: "/avatars/55.png", bg: "#1e1a1a", figure: "#f8d8d8", ring: "#f8d8d8", glow: "#f8d8d880", isActive: true, showIn: "both", rarity: "common" },
  { id: "avatar-56", level: 56, name: "Avatar 56", price: "50", imageSrc: "/avatars/56.png", bg: "#050b0c", figure: "#285868", ring: "#285868", glow: "#28586880", isActive: true, showIn: "admin", rarity: "common" },
  { id: "avatar-57", level: 57, name: "Avatar 57", price: "50", imageSrc: "/avatars/57.png", bg: "#180e1e", figure: "#c878f8", ring: "#c878f8", glow: "#c878f880", isActive: true, showIn: "both", rarity: "common" },
  { id: "avatar-58", level: 58, name: "Avatar 58", price: "50", imageSrc: "/avatars/58.png", bg: "#1a181e", figure: "#d8c8f8", ring: "#d8c8f8", glow: "#d8c8f880", isActive: true, showIn: "both", rarity: "common" },
];
